### DISCUSSION TITLE
Need MPFR static libraries

### DISCUSSION THREAD

**Discussion by tueda** [msys2/MINGW-packages#16746] [Q&A]
I know there is an issue https://github.com/msys2/MINGW-packages/issues/10808, but what I need is the opposite.

I am using [`msys2/setup-msys2`](https://github.com/msys2/setup-msys2) to build statically linked binaries with GitHub Actions. Indeed, the following setup
```yaml
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gmp
            mingw-w64-x86_64-zlib
```
worked well for statically linked binaries.

But if I add `mingw-w64-x86_64-mpfr` to the package list, then it fails:
```
configure:7735: checking for static linking with g++ -static
configure:7760: g++ -o conftest.exe    -static conftest.cpp  -lz -lmpfr -lgmp  >&5
D:/a/_temp/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmpfr: No such file or directory
collect2.exe: error: ld returned 1 exit status
```
Actually, the file list of [`mingw-w64-x86_64-gmp`](https://packages.msys2.org/package/mingw-w64-x86_64-gmp) contains `/mingw64/lib/libgmp.a` while [`mingw-w64-x86_64-mpfr`](https://packages.msys2.org/package/mingw-w64-x86_64-mpfr) does not contain `/mingw64/lib/libmpfr.a`.

Any good ideas?
