### ISSUE TITLE
Does CI only check MINGW64 packages?

### ISSUE THREAD

**Issue by wszqkzqk** [msys2/MINGW-packages#10705]
[.github/workflows/main.yml](https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml) line 105~109:
```
      - uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: MINGW64-packages
          path: C:/_/artifacts
```
It seems that CI only downloads MINGW64 packages to check and may ignore MING32, CLANG64, UCRT64, CLANG32...
Is this by design?
