### ISSUE TITLE
 Linux based Docker image for cross-compilation in CI (non-GitHub)

### ISSUE THREAD

**Issue by AvtechScientific** [msys2/MINGW-packages#11913]
It would be nice if you could create a Linux based docker image that contains MSYS2 and could be used in CI other than GitHub. For example in GitLab, etc.. It would be a more generic approach. You might derive it from Debian, Fedora or Arch Linux (that has the same package manager as MSYS2). It could be used without requiring a Windows virtual machine. Here is an example on how a Fedora docker image is used to cross-compile a GTK application for Windows (without requiring Windows).

https://github.com/manisandro/gImageReader/blob/master/.github/workflows/build.yml

Maybe you can use Wine or add packages like it was done in the above mentioned Fedora based approach.

Thank you very much!

PS: maybe it is possible already to use MSYS2 in GitLab CI without requiring Windows but I miss it?

**Comment by MehdiChinoune** [comment]
GitLab offer Windows image, why not using it?

**Comment by AvtechScientific** [comment]
I would like to help to cross-compile this application:

https://gitlab.gnome.org/GNOME/gnome-text-editor

It doesn't seem to be hosted on regular GitLab... it looks more like Gnome's own instance... So I'm not sure they offer Windows image... Or am I wrong?

Also - do you have an example of GitLab CI that uses MSYS2?

Thank you!

**Comment by Biswa96** [comment]
For general CI guidelines, this can be followed https://www.msys2.org/docs/ci/. Some projects use msys2/mingw in CI. e.g. [gstreamer](https://gitlab.freedesktop.org/gstreamer/gst-ci), [pango](https://gitlab.gnome.org/GNOME/pango), [fontconfig](https://gitlab.freedesktop.org/fontconfig/fontconfig), [inkscape](https://gitlab.com/inkscape/inkscape) etc.

**Comment by AvtechScientific** [comment]
@Biswa96 - thank you, for this info. I saw that page however it seems that all written there is Windows based, which makes MSYS2 less generally applicable as if it were based on Linux image.

**Comment by Biswa96** [comment]
Yes, msys2 is windows based. There are attempts to run msys2 in wine but I don't know if those are fully in usable state. AFAIK, the GitLab CI uses Windows in those repositories.

**Comment by mati865** [comment]
MSYS2 is based on Cygwin which doesn't work under Wine: https://github.com/msys2/MSYS2-packages/issues/682

> However [MinGW can run on Linux](https://github.com/manisandro/gImageReader/blob/master/.github/workflows/build.yml) even without Wine.

No, this is native Linux cross compiler targeting MinGW.

**Comment by MehdiChinoune** [comment]
An example of MSYS2 on gitlab Windows instance
```YAML
default:
  image: ubuntu:20.04

stages:
  - build_ubuntu
  - build_mingw

build-ubuntu:
  stage: build_ubuntu
  script:
    - apt update
    - apt install -y g++-${GCC} cmake ninja-build
    - mkdir build && cd build
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=g++-${GCC}
    - ninja
  parallel:
    matrix:
      - BUILD_TYPE: [Release, Debug]
        GCC: [9, 10]

build-mingw:
  stage: build_mingw
  tags:
    - shared-windows
    - windows
    - windows-1809
  script:
    - Invoke-WebRequest -Uri 'https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe' -OutFile 'msys2.exe'
    - .\msys2.exe -y -oC:\
    - Remove-Item msys2.exe
    - $env:PATH = "C:\msys64\ucrt64\bin;C:\msys64\usr\bin;$env:PATH"
    - bash -lc ' '
    - pacman --noconfirm -Syuu
    - pacman --noconfirm -Syuu
    - $env:CHERE_INVOKING = 'yes'
    - $env:MSYSTEM = 'UCRT64'
    - pacman -S --noconfirm mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-ninja
    - mkdir build
    - cd build
    - cmake .. -GNinja
    - ninja
```
