### ISSUE TITLE
Compilation troubles with zmq crate with msys2

### ISSUE THREAD

**Issue by buxx** [msys2/MINGW-packages#16397]
Hello ! I'm game developer of OpenCombat open source game (https://github.com/buxx/OpenCombat).

I have many troubles with compiling my game for windows because using zmq crate (https://docs.rs/zmq/latest/zmq/).

I use this `msys2/setup-msys2` action (ex. https://github.com/buxx/OpenCombat/blob/master/.github/workflows/rustbuild.yml) to install `mingw-w64-x86_64-zeromq` :

```yaml
jobs:  
  check-msys-mingw64:
    [...]
      - name: Setup msys2 dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-cc mingw-w64-x86_64-rust mingw-w64-x86_64-zeromq mingw-w64-x86_64-pkg-config --needed
```

But, build fail on the following :

```
thread 'main' panicked at 'Unable to locate libzmq:
  Could not run `"pkg-config" "--libs" "--cflags" "libzmq" "libzmq >= 4.1"`
  The pkg-config command could not be found.
```

Any idea about why pkg-config don't found libzmq ?
